### ISSUE TITLE
`PhBaseWorkChain`: the new `set_qpoints` is untested and broken

### ISSUE THREAD

**Issue by bastonero** [aiidateam/aiida-quantumespresso#1004]
A few lines in `PhBaseWorkChain` added recently are not covered by the test suite and have some typos.
The following:
https://github.com/aiidateam/aiida-quantumespresso/blob/b517686df8cd33765ef12cbf430620ea8e94f137/src/aiida_quantumespresso/workflows/ph/base.py#L186
should be:
`structure = self.ctx.inputs.parent_folder.creator.output.output_structure`
or 
`structure = self.inputs.ph.parent_folder.creator.output.output_structure`
and also
https://github.com/aiidateam/aiida-quantumespresso/blob/b517686df8cd33765ef12cbf430620ea8e94f137/src/aiida_quantumespresso/workflows/ph/base.py#L188
should be either
`structure = self.ctx.inputs.parent_folder.creator.inputs.structure`
or 
`structure = self.inputs.ph.parent_folder.creator.inputs.structure`

**Comment by mbercx** [comment]
Thanks @bastonero! I also noticed this last week when trying to run the electron-phonon work chains, but haven't had the time to push (and add tests for) my fix.

Since this effectively breaks the `PhBaseWorkChain`, I say we fix this asap and do a patch release. If you're not working on a PR already, I'll push my fix.

**Comment by bastonero** [comment]
I still haven't worked out the tests either, and just fixed it locally for myself. I can do the PR and you work out the minor release?
