### ISSUE TITLE
PARSINGFAILED Error

### ISSUE THREAD

**Issue by vamshimohank** [aiidateam/aiida-quantumespresso#163]
I am trying to do a simple scf run. This used to work quite will until I updated to the latest version. I followed the instructions (hopefully correctly) for the update. 

I get the following error. could you please help me to fix this. 

Regards
Vamshi 

*** 1628134: PARSINGFAILED
*** (empty scheduler output file)
*** (empty scheduler errors file)
*** 1 LOG MESSAGES:
+-> REPORT at 2018-06-14 11:22:40.372376+00:00
|   [1628134|JobProcess_aiida_quantumespresso.calculations.pw:PwCalculation|on_except]: Traceback (most recent call last):
|     File "/Users/katukuri/.virtualenv/aiidapy-py2.7/lib/python2.7/site-packages/plumpy/process_states.py", line 212, in execute
|       result = self.run_fn(*self.args, **self.kwargs)
|     File "/Users/katukuri/Codes/aiida_core/aiida/work/job_processes.py", line 522, in retrieved
|       exit_code = execmanager.parse_results(self.calc, retrieved_temporary_folder)
|     File "/Users/katukuri/Codes/aiida_core/aiida/daemon/execmanager.py", line 409, in parse_results
|       exit_code, new_nodes_tuple = parser.parse_from_calc(retrieved_temporary_folder)
|     File "/Users/katukuri/Codes/aiida_core/aiida/parsers/parser.py", line 89, in parse_from_calc
|       return self.parse_with_retrieved(retrieved)
|     File "/Users/katukuri/.virtualenv/aiidapy-py2.7/lib/python2.7/site-packages/aiida_quantumespresso/parsers/pw.py", line 69, in parse_with_retrieved
|       dir_with_bands = temporary_folder.get_abs_path('.')
|   AttributeError: 'str' object has no attribute 'get_abs_path'

**Comment by sphuber** [comment]
When you say you updated to the latest version, are you referring to `aiida-core`? If that is the case, i.e. you are using the `develop` branch of `aiida-core` and not one of the `v0.12*` versions, than you also have to update your `aiida-quantumespresso` version. The latest release and `develop` branch of `aiida-quantumespresso` are only compatible with `aiida-core<=0.12.*`. If you want to use the latest `aiida-core` from the `develop` branch, you will need to check out the branch `release_v3.0.0` of `aiida-quantumespresso`. But be aware that since this an active development branch and has not been released yet, things may change quickly
