### ISSUE TITLE
Add HDF5 output compatibility

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#222]
It might be sufficient to change parameter 'charge_density', which is normally set to "./charge-density.dat", to be "./charge-density.hdf5" if appropriate. This value is under `<CHARGE-DENSITY iotk_link="./charge-density.dat">` in the old XML format, and absent (implied/hardcoded) in the new XML format.

**Comment by mbercx** [comment]
@sphuber perhaps this is relevant for your full-XML work?

**Comment by sphuber** [comment]
I would be tempted to close this, similar to the other issue. Apparently there hasn't been a need for this in 6 years. Can always reopen if we find a real use-case.

**Comment by mbercx** [comment]
I'd have to understand what the `.charge-density.dat` actually does in that parser code, since the charge density is not retrieved by default. I've already been stashing HDF5 charge densities plenty, but this of course requires no support here.

Once we clean up the parser code we can have a look again if it comes up. By far HDF5 >>> `.dat`.
