### ISSUE TITLE
Add parent calculation as alternative input to NamelistsCalculation classes?

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#279]
Notes taken from `calculations/dos.py` on how to possibly do this:

```python
    
    # TODO: if you want to be able to specify an input calculation (rather than a folder),
    #       you must add this as an input to the NamelistsCalculation with non_db=True, like this:
    # from aiida.orm import CalcJobNode
    # spec.input('parent_calculation', valid_type=CalcJobNode, required=False, non_db=True)
    # TODO: Then you must add the following logic to the prepare_for_submission method
    #       (note that you can't actually modify self.inputs, because it's a 'AttributesFrozendict')
    # def prepare_for_submission(self, folder):
    #     """
    #     Set the parent folder if necessary, or raise if neither parent_folder nor parent_calculation were given.
    #     Then call define() from the super class.
    #     """
    #     from aiida.common import InputValidationError
    #     if 'parent_folder' in self.inputs and 'parent_calculation' in self.inputs:
    #         raise InputValidationError('You cannot specify both inputs \'parent_folder\' and \'parent_calculation\'.')
    #     elif 'parent_folder' in self.inputs:
    #         pass
    #     elif 'parent_calculation' in self.inputs:
    #         parent_calc = self.inputs.parent_calculation
    #         try:
    #             # TODO: check that the calc's process_type is quantumespresso.pw 
    #             parent_folder = parent_calc.get_outgoing(node_class=RemoteData, link_label_filter='remote_folder').one().node
    #         except ValueError:
    #             raise InputValidationError('Parent calculation does not have a remote folder output node.')
    #         self.inputs['parent_folder'] = parent_folder
    #     else:
    #         raise InputValidationError('Either \'parent_calculation\' or \'parent_folder\' must be in the inputs.')
    # 
    #     super(DosCalculation, self).prepare_for_submission(folder)
    # 
    # TODO: ... except that it won't work, because I can't validate the process_type of the parent calc from the
    #  NamelistsCalculation class: the acceptable types may change according to what is the concrete
    #  type (e.g. DosCalculation, ...).
    # TODO: Maybe this can be done with a validator for the input port? (see plumpy.ports.InputPort.__init__())
```

**Comment by odarbelaeze** [comment]
As a way to signal restarts, similar to the `pw` and `cp` ones?

**Comment by borellim** [comment]
For instance, both dos.x and pw2wannier.x need the output folder from a pw.x calculation. Right now it's easier to define the input spec for their calculation plugins to take a FolderData or a RemoteData, but we **might** want to take a calculation instead (or both). The CLI launcher for dos.x (`aiida_quantumespresso/cli/calculations/dos.py`) shows how one gets from a calculation to its output folder, but there are some complications in adding a calculation to the spec, as explained above.

**Comment by sphuber** [comment]
The problem with the approach you sketched is that you will lose provenance, which makes it automatically disqualifying for me. By specifying the calculation input as `non_db=True`, one ensures there will be no link from it as an input, and that is the point, because you cannot have an input link from a process node to another process node. However, you *are* using some of its outputs for the new calculation, but those will not be recorded as such in the provenance graph.
If you are using those for a restart they simply *have* to be recorded as inputs.

One could imagine a pre-serialization option in the `input` port definition that will transform the incoming `CalcJobNode` into the output nodes required for a restart, but brings a whole lot of problems with it. For example, what links should be used for those input nodes? And this makes the spec opaque, i.e. just by looking at it, it is not directly clear what inputs it needs as some are hidden in the calculation serializer. All in all, I think the best option is that the `CalcJob` just specifies the exact data nodes it expects as inputs and does not support process nodes. Unwrapping a calculation into the nodes required for a restart is ultimately not that complicated.

**Comment by sphuber** [comment]
@borellim is this answered and can be closed? Or are there still options you wanted to discuss and investigate?
