### ISSUE TITLE
Slightly negative occupations cause sanity check to fail

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-quantumespresso#399]
Running a calculation with ``occupations='tetrahedra'``, I obtain slightly negative (roughly 1e-8) occupations. 

This doesn't seem to be a problem, but causes the sanity check in the base workchain to fail with 
```
 BandsData<4895> has invalid occupations: Occupation of 0.0 at n=15 after lumo lkn<-7.536307628800891e-09,14,0>
```

Would it be appropriate to add a small margin of error on that test? For example in https://github.com/aiidateam/aiida-quantumespresso/blob/develop/aiida_quantumespresso/utils/bands.py#L48, change to ``if occupation > lumo_occupation + threshold:``?

**Comment by sphuber** [comment]
That would be one solution. Another one, not sure if it is better, is to maybe set the `lumo_occupation` when found to `0.0` if it is negative. I am not sure if it ever makes sense for a user to set `threshold` to a negative number, for example. Are negative occupations typical?

**Comment by greschd** [comment]
Yeah that would make sense. I don't know why the occupation is negative, to be honest. As far as I can tell, it's just a small numerical error -- I mean, physically a negative occupation doesn't really make sense, does it?

**Comment by sphuber** [comment]
> I mean, physically a negative occupation doesn't really make sense, does it?

Not really, but I think there are some smearing methods that may have some side effects. For example, I think with marzari-vanderbilt smeaing occupations just below the fermi energy can be more than one, which also does not really have physical meaning.

**Comment by greschd** [comment]
That probably means the sanity check in the workflow should depend on which ``occupations`` is used, right?

Looking at that code, I think the ``:raises ValueError: if the occupations are not monotonically decreasing at all k-points between LUMO and HOMO`` from the description also isn't really done: It only starts comparing occupations above LUMO.

**Comment by sphuber** [comment]
Yes the comment is incorrect, it should state that it will raise if any occupation after the LUMO is bigger than the LUMO occupation. Discussing with @giovannipizzi we think that your suggestion is better than mine, but there is still a complication. With methfessel-paxton smearing often the occupations are actually negative after the fermi energy and it can be quite deep. Really what I wanted to accomplish with this test is that after the LUMO (i.e. first band where occupation < threshold) all subsequent bands are smaller than that. However, due to numerical noise they can be slightly bigger just after. The idea now is to change the condition that after the LUMO (decided as the first band to have occupation < threshold), the occupation of all bands should be below 2*threshold. We cannot use just the threshold, because if the LUMO happens to be exactly or very close to the threshold, numerical noise can surpass it. Sounds reasonable?

**Comment by greschd** [comment]
Sounds very good to me :+1:
