### ISSUE TITLE
Restart mode for bands calculations

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-quantumespresso#404]
Since I'm relatively new to using QE, I'm confused as to why the ``PwBandsWorkChain`` uses ``restart_mode='restart'`` in the bands calculation. From the ``pw.x`` input specification (https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm57), it seems the recommended way of doing it is ``from_scratch``, which sets ``startingpot`` to ``'file'`` for bands calculations.

What is the reason for using ``restart`` here?

**Comment by sphuber** [comment]
Note that I have not gotten around to rigorously testing the `PwBandsWorkChain` functionality yet, so there may be stupid mistakes errors in the logic. Since the summer I have been working my up starting from the `PwParser` to the `PwBaseWorkChain` and most recently the `PwRelaxWorkChain`.

I think that using `restart` here eventually may do the right thing, because we also pass the `parent_folder` with the charge density computed in the `scf` step. I'm assuming Quantum ESPRESSO with the combination `calculation=bands` and `restart_mode=restart` understand that the potential should be computed from the present files.

Looking at the stdout of a bands calculation run through the workchain, I do see this in the output:
```
WARNING: "startingwfc" set to atomic+random may spoil restart
```
The `startingwfc` is an `ELECTRON` card input and its default is indeed `atomic+wfc` which for a bands calculation indeed does not make sense.
Further down in the output I find:
```
     The potential is recalculated from file :
     ./out/aiida.save/charge-density.dat

     Starting wfc are    8 randomized atomic wfcs
```
So the potential is recalculated from file, which according to the docs is also the default and is only thing that makes sense for a bands (nscf) calculation. However, it seems the wavefunctions are initialized randomly as the default also suggests. Honestly, I am not sure if this is a problem or not. I think it should give the same answer if we used the files written from the scf. I guess why we don't specify by default to read the wavefunctions is that they are not always stored long term whereas the charge density we sometimes do. If the potential can be recomputed from the charge density, then that should allow us to uniquely solve the actual wave functions again by diagonalization. The only downside here is that we have to recompute the wave functions so we lose computing time but the final computed bands should be correct.

Again, I am not a 100% sure and this is something I was planning on tackling soon, after having "finalized" the relax workchain. If you have any tests/proof to the contrary, those are most welcome and we can improve the workchain.

**Comment by sphuber** [comment]
I have been looking into this in more detail with @giovannipizzi and performed the simple test of running an SCF followed by a `calculation = 'bands'` calculation for three cases of `restart_mode`:
* unspecified, so default
* `from_scratch`
* `restart`
The default seems to be `from_scratch` as the docs say and we have confirmed this by looking in the source code. Using `restart` does not seem to affect the final answer so should not hurt but it is indeed better to not set it if not necessary.

Instead, `restart` can and should be used if a `bands` calculation was interrupted and shut down cleanly. In that case it will have written the computed k-points to disk and in the restart continue where it left of.
