### ISSUE TITLE
Smearing type not always present in XML output

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-quantumespresso#415]
The XML output does not always contain the smearing type. In `aiida_quantumespresso/parsers/parse_xml/pw/parse.py`, we assume that the smearing type is always present when `occupations != 'from_input'`, however this is not true. Is this a bug in QE or is our logic incorrect? Even if it is a bug in QE, how can we work around it?

See: https://github.com/aiidateam/aiida-quantumespresso/blob/6fff0c2d241beadd2f9640d284b99692fd1071e4/aiida_quantumespresso/parsers/parse_xml/pw/parse.py#L153-L165

**Comment by greschd** [comment]
Does this happen only when the smearing is not given in the input? In that case, we could just fall back to the QE default, ``gaussian``.

**Comment by greschd** [comment]
Shouldn't ``smearing_method`` only be true if ``occupations`` is set to ``smearing``? I don't see why there should be a smearing output for the tetrahedron method(s), or fixed occupations.

**Comment by greschd** [comment]
Yeah, probably better to just set it to ``None`` in that case (or not create the ``smearing`` output, if that's possible). But, I think the parser should only fail if ``occupations`` are set to ``smearing`` and ``smearing`` is not found in the output.

**Comment by sphuber** [comment]
Taking a look at the code now it seems that these keys only need to be determined when `include_deprecated_keys` is `True`. Honestly, I think this gives way too much extra code and work around just keep three old keys in the results dictionary that do not even make sense anyway _and_ are even redundant.

**Comment by sphuber** [comment]
There is another problem/question regarding the units. According to the documentation, the unit for `degauss` in the input is Rydberg. The XML output states that all energies are in Hartree, unless explicitly stated otherwise. The degauss in the XML is reported the exact same as in the input, but it does not say explicitly that it is Rydberg. So the XML output is technically wrong. I guess the old parser also stored the values in Rydberg, so we can keep it. But really, all these units are a mess. There is bound to be mistakes all over the shop

**Comment by greschd** [comment]
Seems like that is an issue to be reported to QE, right? Either the input or output description needs fixing.
