### ISSUE TITLE
Setting pw.x parallel execution parameters (npool, ndiag, ...)

### ISSUE THREAD

**Issue by bonfus** [aiidateam/aiida-quantumespresso#427]
I'm sorry to bother you with all these issues, if there's a better place to ask for support please let me know.

I got stuck when trying to set the parallel execution parameters for pw.x.
I basically only need to set _npools_ and _ndiag_. Here's a snippet of my code:

    from aiida_quantumespresso.utils.resources import get_default_options

    builder = WorkflowFactory('quantumespresso.pw.relax').get_builder()
    default_options = get_default_options(1, 24*60*60, True)

    # How to add npool and ndiag to default_options ??? Should it be added somewhere else?

    builder.base.pw.metadata.options = default_options

The inputs I'm dealing with makes it very easy to guess the right values for those to parameters so it would be great to put exactly the numbers I want in the jobscript.

**Comment by sphuber** [comment]
Not to worry. We don't have a mailing list yet for `aiida-quantumespresso` like we have for you `aiida-core`. Feel free to send me an email directly if you have questions. For the command line options, you can pass them in the `settings` input node under the key `cmdline`, which should be a list of options. For example:
```
settings = Dict(dict={'cmdline': ['-nk', '4', '-ndiag', '1']})
```
You can then pass this as an input to `PwCalculation`.

Note that in #405 we are discussing of making the parallelization flags an input node of its own, instead of having them "hidden" in the `settings` input.
