### ISSUE TITLE
cell_dofree='volume' not possible

### ISSUE THREAD

**Issue by BeZie** [aiidateam/aiida-quantumespresso#456]
Dear all,

currently a cell_dofree  = 'volume'  vc-relaxation is not possible as it requires ibrav=1. ibrav=0 is automatically set and cannot be overwritten by the user.

Best regards,
Benedikt

**Comment by sphuber** [comment]
Thanks for the report Benedikt. Unfortunately the `ibrav` is currently indeed automatically set and not allowed to be specified manually. The original reasoning was that because it would be difficult to automatically adapt the ibrav in workflows where the cell is changing. This functionality has been requested before though and I have opened issue #347  for it. If you do not mind, I will close this issue and we can continue the discussion there
