### ISSUE TITLE
parser for QE 6.5

### ISSUE THREAD

**Issue by qiaojunfeng** [aiidateam/aiida-quantumespresso#459]
The current XML parser does not work under QE 6.5, it will report
```
(aiida) max@qmobile:~$ verdi process report 1677
*** 1677: None
*** (empty scheduler output file)
*** (empty scheduler errors file)
*** 2 LOG MESSAGES:
+-> ERROR at 2020-02-11 16:04:12.913365+00:00
 | parser returned exit code<322>: The XML output file has an unsupported format.
+-> ERROR at 2020-02-11 16:04:12.910322+00:00
 | The XML output file has an unsupported format.
```

The reason is that QE 6.5 changes its output XML schema to 
```
<?xml version="1.0" encoding="UTF-8"?>
<qes:espresso xsi:schemaLocation="http://www.quantum-espresso.org/ns/qes/qes-1.0 http://www.quantum-espresso.org/ns/qes/qes_191206.xsd" Units="Hartree atomic units" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:qes="http://www.quantum-espresso.org/ns/qes/qes-1.0">
```
while the header of QE 6.4 is
```
<?xml version="1.0" encoding="UTF-8"?>
<qes:espresso xsi:schemaLocation="http://www.quantum-espresso.org/ns/qes/qes-1.0 http://www.quantum-espresso.org/ns/qes/qes_190304.xsd" Units="Hartree atomic units" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:qes="http://www.quantum-espresso.org/ns/qes/qes-1.0">
```

The difference is `qes_190304.xsd` and `qes_191206.xsd`
The only difference between the two xsd is line 226
```
<attribute type="string" name="alternative_axes" use="optional" />
```

I just downloaded the new xsd from QE git repository
`https://raw.githubusercontent.com/QEF/qeschema/master/qes_191206.xsd`
and put it under `aiida_quantumespresso/parsers/parse_xml/pw/schemas/` and it worked.
like this: https://github.com/qiaojunfeng/aiida-quantumespresso/commit/6dc5dd3745058f817a073669dcf68d31d06ab9c6

But I am not sure if this will induce other problems to the plugin.
A test case is attached, and two XML outputs.

[test.tar.gz](https://github.com/aiidateam/aiida-quantumespresso/files/4186974/test.tar.gz)

**Comment by ConradJohnston** [comment]
Important find @qiaojunfeng !

@sphuber - Is there a systematic way in place of keeping in sync with new QE releases? It's annoying that the schema keeps changing, but I guess less annoying than when changes were made to the stdout.

**Comment by sphuber** [comment]
Thanks for the very clear and detailed report @qiaojunfeng ! This is in a sense expected, QE 6.5 comes with a new version of the XML schema since they apparently had to make some changes. Luckily, since they are now using a schema based XML, incorporating the changes into our plugin should be as easy as simply including the new schema file in the repository, as you have noticed. I have written the code such that it will automatically detect the schema version used for the output file and it will try to find the schema. I decided against some automated way that will try to automatically download the schema from the internet, because I do not like code automatically  downloading stuff from the web in the background. So the solution is really just to add the schema file and add a test.

**Comment by qiaojunfeng** [comment]
Hi, here is the `aiida.out`, `aiida.xml`, and `aiida.in` for QE6.4 & QE6.5.

[in_out.tar.gz](https://github.com/aiidateam/aiida-quantumespresso/files/4191702/in_out.tar.gz)

**Comment by ltalirz** [comment]
Would it be possible to make a new release of aiida-qe so that we can ship it with the Quantum Mobile to be released in the 1st week of March (and avoid to downgrade QE to 6.4?)?
