### ISSUE TITLE
Fix resource validation in all workchains

### ISSUE THREAD

**Issue by dpshoema** [aiidateam/aiida-quantumespresso#528]
I was running through the tutorials and all my local submitted jobs hang at

` PwCalculation    ⨯ Excepted       Waiting for transport task: upload`

Running the test script (aiida-quantum-espresso calculation launch ...) helped give a more specific error

`TypeError: At least two among num_machines, num_mpiprocs_per_machine or tot_num_mpiprocs must be specified`

So updating the script to 

`builder.metadata.options.resources = {'num_machines': 1,'num_mpiprocs_per_machine': 1}`

Fixed the problem. It was actually quite hard to pin down since I never saw the resources error when submitting to the daemon. Not sure if this is only my problem or more common. If the latter, does the example script need to be updated?

**Comment by sphuber** [comment]
Thanks for the report. The documentation, including the examples is unfortunately outdated here and there due to the big updates since `aiida-core==1.0.0`. I haven't had the time yet to correct it. The problem you faced should already be made easier with a more recent version of AiiDA. Since then, the resources are validated before actually submitting it. So you would see the error that you saw when running through the `aiida-quantumespresso` CLI. Unfortunately, the question of the resources is not as easy, as it depends on the scheduler what constitutes "correct resources". There is an open issue: https://github.com/aiidateam/aiida-core/issues/3887

**Comment by BeZie** [comment]
@sphuber 
You are probably already aware of it but the current versions of the base workflows (e.g. ph) are checking for num_machines, but now some scheduler must not have num_machines set, e.g. the SGE scheduler.  Not sure if I should open a new issue or keep it here.

**Comment by sphuber** [comment]
Thanks for the heads-up @BeZie . I have fixed the problem in `aiida-core` which was released in v1.3 last week. I will try to find the time soon to update the workflows here as well.

**Comment by mbercx** [comment]
Pretty sure this was fixed in AiiDA core some time ago, along with the work in https://github.com/aiidateam/aiida-quantumespresso/pull/683. Feel free to re-open in case I'm mistaken.
