### ISSUE TITLE
 aiida-quantumespresso expects a bands output

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-quantumespresso#543]
Hi everyone,

I think there is an issue with sanity_check_insufficient_bands. Currently it 'demands' that there be a output_band node. E.g. 

```
    @process_handler(exit_codes=ExitCode(0))
    def sanity_check_insufficient_bands(self, calculation):
        """Perform a sanity check on the band occupations of a  successfully converged calculation.

        Verify that the occupation of the last band is below a certain threshold, unless `occupations` was explicitly
        set to `fixed` in the input parameters. If this is violated, the calculation used too few bands and cannot be
        trusted. The number of bands is increased and the calculation is restarted, starting from the last.
        """
        from aiida_quantumespresso.utils.bands import get_highest_occupied_band

        # Only skip the check on the highest band occupation if `occupations` was explicitly set to `fixed`.
        if calculation.inputs.parameters.get_attribute('SYSTEM', {}).get('occupations', None) == 'fixed':
            return

        try:
            bands = calculation.outputs.output_band
            get_highest_occupied_band(bands)
        except ValueError as exception:
```

For me, this breaks my calculations because I run with output bands disabled. 

I think this can be solved with a simple try/except e.g. 

```
try:
    bands = calculation.outputs.output_band
except NoOutputBand  #Not sure what the best exception would be
    return 

```

**Comment by greschd** [comment]
I think the correct exception to catch would be `aiida.common.exceptions.NotExistentAttributeError`, or simply the Python built-in `AttributeError`.

I'm wondering if we should explicitly check that `settings['no_bands']` was set to `True` to distinguish this case from e.g. when the calculation _should have_ created bands, but simply failed to do so. Maybe that's already captured in the checks of the `PwCalculation`, though.

**Comment by DanielMarchand** [comment]
Yeah agreed, I think directly checking the settings would be the correct way to go about this...

**Comment by greschd** [comment]
FYI, I think you can work around this with the current code versions by disabling this specific handler. Here's the `aiida-core` PR that added this functionality: https://github.com/aiidateam/aiida-core/pull/3786

**Comment by sphuber** [comment]
I think that the workchain should not have to check the `no_bands` because the sanity check should only be triggered if the `PwCalculation` finished with exit status 0, which means all outputs that are supposed to be there, are there. Since the `output_band` is not required, the workchain simply should not assume it exists and skip the check if the output node is not there. 

The question is if the `no_bands` setting should still be checked in the parser, because currently it is not. I am not sure that it should be though. The `no_bands` setting was introduced to prevent unnecessary data being stored for users who do not require the info. It was not introduced as a switch to prevent calculations from failing if the bands could not be parsed in cases where that is actually expected. If `no_bands=True` the relevant files are not even retrieved and so also not parsed. What we could think of adding is a check that if the band files are not there but `no_bands=False` and then return an error. This is independent of this issue though.

**Comment by greschd** [comment]
> 
> 
>  What we could think of adding is a check that if the band files are not there but `no_bands=False` and then return an error. This is independent of this issue though.

Agreed, this is the only case where a non-zero exit code should be returned. Also agreed that the calculation is the better place to put this check.
