### ISSUE TITLE
Stress is not being parsed

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-quantumespresso#547]
Hi Everyone, 

I'm having an issue where stresses are not being parsed from calculations. Please find an example attached as a  [google drive link](https://drive.google.com/file/d/1ucg_waFa7AwK1oPr5NZQSuCvwj_KswFW/view?usp=sharing). 

EDIT: I'm pretty sure it is a bug, as I can see the stress is present in the raw output file when I run 
$verdi calcjob outputcat CALCID | grep -i -A3 stress

**Comment by sphuber** [comment]
The stress is parsed but it is not stored in the `output_parameters` node, but in the `output_trajectory` one. This is because the stress is computed at every step of the trajectory (in the case of relax/md there are potentially more than one) and so it is stored in an `ArrayData`. You can retrieve it through `node.outputs.output_trajectory.get_array('stress')`.

**Comment by DanielMarchand** [comment]
Ok, great thanks a lot. (In the old version I was using it was stored in the output_parameters).
