### ISSUE TITLE
Exception catching incompatible with `aiida-core==1.2`

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-quantumespresso#556]
In some places, we catch `AttributeError`, for example 

https://github.com/aiidateam/aiida-quantumespresso/blob/develop/aiida_quantumespresso/workflows/pw/base.py#L339

However, prior to https://github.com/aiidateam/aiida-core/pull/3985, this would raise a `NotExistent` error that does _not_ derive from `AttributeError`. As such, the above line is incompatible with the `1.2.x` versions of `aiida-core`.

Possible options: 
- fix all instances where such an `AttributeError` is caught
- explicitly support only `aiida-core >= 1.3`

The tests already cover this case - I found it on a dev environment that still had older `aiida-core` installed. Maybe CI should include the oldest-supported AiiDA version in addition to the latest one.

**Comment by sphuber** [comment]
The fix would be to replace those with `NotExistent`, correct? We can certainly do this and won't be too much work, question is just if it is worth it. I think it is more intuitive to be catching `AttributeError` and it saves an import. I would be fine with requiring `aiida-core~=1.3` since it is all backwards compatible in principle. In addition, I am hoping to be merging a feature with `1.4` soon that will  allow me to finally finish the `aiida-pseudo` plugin which I will then add support for here, requiring to up the minimum level of `aiida-core` anyway. So I would be tempted to the latter.

**Comment by greschd** [comment]
Yeah that was more or less my thinking also - but I don't know if there is still a significant user base on `1.2`.
