### ISSUE TITLE
AiiDA registry points out issues with setup.json

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-quantumespresso#583]
```
  >> WARNING: Missing classifier 'Framework :: AiiDA'
  >> WARNING: Entry point 'spinorbithydrogen' does not start with 'quantumespresso'
  >> WARNING: Entry point 'noncollinearhydrogen' does not start with 'quantumespresso'
```

The first one is easy to fix; and I also suggest to fix the other ones - unless there is a very good reason to put those entry points into the global namespace without a `quantumespresso` prefix

**Comment by sphuber** [comment]
Thanks @ltalirz I will open a PR to address the first warning. The entry points were added in 031b92b9c85ed01588de332f039af05738607375 and I think the reasoning to not prefix them was because essentially they are an extension to the:
```
"aiida.tools.data.orbitals": [
    "orbital = aiida.tools.data.orbital.orbital:Orbital",
    "realhydrogen = aiida.tools.data.orbital.realhydrogen:RealhydrogenOrbital"
],
```
entry points of `aiida-core`. I also asked the question during the review of PR #546 whether these should go into `aiida-core`:

> This is more directed at greschd and  qiaojunfeng : does the solution of the SpinorbitHydrogenOrbital and NoncollinearHydrogenOrbital solve your use case as well, as described in the issue on aiida-core? If so, should we maybe add this to aiida-core to be with the rest of the orbitals? Then again, we are planning to actually move those out of aiida-core for v2.0 to a plugin package (to be decided which), so maybe including them here for now is just as well.

But we decided to keep it here, but without the `quantumespresso` prefix. Once we move the other one to a dedicated package, we will move these as well. Would that be okay?

**Comment by ltalirz** [comment]
> Once we move the other one to a dedicated package, we will move these as well. Would that be okay?

Thanks for the clarification, sounds good!
I guess at that point they may anyhow get a prefix based on the name of the package they are moving into.
