### ISSUE TITLE
projwfc.x error 340

### ISSUE THREAD

**Issue by hezhengda** [aiidateam/aiida-quantumespresso#617]
Hi Aiida team,

Right now I can successfully run projwfc.x calculation. But I meet some errors regarding to the parser of the results.

The folder on my cluster looks like:
![image](https://user-images.githubusercontent.com/26743576/99660216-57046700-2a62-11eb-851f-9a6f5d54e7a9.png)

So the calculation went well, but the parser didn't work.

The output by `verdi list report` is listed in below:

```
*** 174 [PDOS of beta-NiOOH]: None
*** (empty scheduler output file)
*** Scheduler errors:
(OK) Loading CHEMISTRY environment
(OK) Loading qe 6.5
(OK) Loading CHEMISTRY environment
(WW) qe/6.5 already loaded, doing nothing
srun: TOPOLOGY: warning -- no switch can reach all nodes through its descendants.Do not use route/topology

*** 3 LOG MESSAGES:
+-> ERROR at 2020-11-18 21:09:45.776136+00:00
 | Error parsing bands and projections: Could not get parent calculation of input folder: no entries found
+-> ERROR at 2020-11-18 21:09:45.780302+00:00
 | An exception was raised parsing bands and projections.
+-> WARNING at 2020-11-18 21:09:45.785551+00:00
 | output parser returned exit code<340>: An exception was raised parsing bands and projections.
```

Could you tell me what went wrong? And how can I fix this?

Thanks,
ZDH

**Comment by sphuber** [comment]
The problem is right there in the report:

> Error parsing bands and projections: Could not get parent calculation of input folder: no entries found

The node that you passed as the `parent_folder` input does not have a parent calculation. I suspect this is because you used the solution you came up with in a different issue where you created a `RemoteData` manually. Since you did not create the link to the calculation that created it, the projwfc parser cannot find it. Note that if you use the solution I proposed, by just using `parent_calc.outputs.remote_folder` to use as the `parent_folder` then you won't have this issue.

**Comment by hezhengda** [comment]
Thanks for the answer.
