### ISSUE TITLE
Can `PwBaseWorkChain` be used like `PwCalculation`?

### ISSUE THREAD

**Issue by atztogo** [aiidateam/aiida-quantumespresso#692]
I use aiida-core v1.6.3, aiida-quantumespress v.3.4.1.
I succeeded to run `PwCalculation`. Can I use `PwBaseWorkChain` similarly to `PwCalculation`?

I set structure, parameters, metadata.options.resources (I use sge), code, and pseudos at `builder.pw`, and `builder.kpoints`, then `run(builder)`, but I could not succeed to run the WorkChain,

**Comment by sphuber** [comment]
Hi @atztogo . Thanks for the report. I think this might be a problem with you using the `SgeScheduler`. There was a bug in the resource validation of the base workchain which I fixed in #683 but that hasn't been released yet (the PR to release it with 3.4.2 is open and should be released soon though). Could you try installing the develop branch of `aiida-quantumespresso` and try again? Thanks.

**Comment by atztogo** [comment]
@sphuber, develop branch (9b083e78c) worked. Thanks!
