### ISSUE TITLE
Alternative `process_handler` for Cholesky error

### ISSUE THREAD

**Issue by bastonero** [aiidateam/aiida-quantumespresso#880]
The "Choelsky error" is probably one of the most strange errors to handle in QuantumESRPESSO, since apparently there is not a straightforward solution. Currently, this error is handled by changing the `diagonalization` from `davidson` (default) to `cg`. Nevertheless, the conjugate gradient algorithm is VERY slow, and an other solution is desirable.

I tested for quite a while now a possible general alternative. Since QE exploits parallel diagonalization over N^2 cores, this might be affected by quite some numerical noise. Therfore, I tried to force this to be performed over 1 only core, ending up all the time to a successful run of the `pw.x` code. This alternative is still MUCH faster than the current CG solution, which can still be employed as a "last resort". 

This would mean  adding `['-ndiag','1']` to the `pw.settings` `cmdline` key in a consistent way.

Let me know your thoughts, and I hope this could help to have a more effective handler.

**Comment by sphuber** [comment]
Are you saying that the only time a Cholesky error can come up is when `ndiag` is set to something other than `1`? Or can this also happen when this is not set? Is QE automatically setting this parallelization parameter internally?

**Comment by bastonero** [comment]
No, what I meant is that, in my experience, I could handle successfully many times this error just changing/setting `ndiag` to `1`. QE is internally setting this parameter automatically if not specified. Actually, from QE v.7.1 also all the other parameters are chosen automatically, again if not set from inputs.

**Comment by mbercx** [comment]
Thanks @bastonero! I agree the `cg` diagonalisation method is not the best since it's so slow. I kind of accepted this at the time because the Cholesky error was rare enough for my calculations, and were still supporting QE < v6.6 so I couldn't switch to e.g. `paro` since this [is only available from v6.6](https://gitlab.com/QEF/q-e/-/releases#new-in-v-66). (also see the related issue https://github.com/aiidateam/aiida-quantumespresso/issues/830)

It's interesting to see the parallelization affects this error. I'd still be in favor of simply switching to `paro` in the error handler now, since we've dropped support for QE <= v6.5. I think `paro` is also quite fast, but I haven't tested it extensively to be honest.

**Comment by bastonero** [comment]
Yes, also this is a good alternative @mbercx ! For sure, anything is better than `cg`!
