### ISSUE TITLE
q2r "output_parameters"

### ISSUE THREAD

**Issue by hungdt** [aiidateam/aiida-quantumespresso#971]
Hello.

I am trying the q2r calculation and get the error
`Error: invalid value uuid: 2f4cb14b-ad18-4587-9613-7c75d1d6b4e7 (unstored) specified with label output_parameters: Error validating output 'uuid: 2f4cb14b-ad18-4587-9613-7c75d1d6b4e7 (unstored)' for port 'outputs': Unexpected ports {'output_parameters': <Dict: uuid: 2f4cb14b-ad18-4587-9613-7c75d1d6b4e7 (unstored)>}, for a non dynamic namespace
`
I found that in Q2rParser.parse(), there is a line
`self.out('output_parameters', Dict(parsed_data))`
but there is no definition of `output_parameters` in the q2r calculation.

Should the line in Q2rParser.parse() be deleted?

**Comment by sphuber** [comment]
Thanks for the report, the line was added in https://github.com/aiidateam/aiida-quantumespresso/commit/1c223c78f0a2eda38089a08d9f21626f49d2fd6b but indeed the `Q2rCalculation`does not declare the `output_parameters` output, and so the code excepts. If it makes sense to have this output, instead of removing it from the parser, we could also just add the output to the spec of the `Q2rCalculation`.
